name: soil_moisture_swir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23
  - pandas
  - matplotlib
  - bokeh=3.1
  - statsmodels
  - dominance_analysis=0.6.3
  - scipy
  - seaborn
  - scikit-learn
  - plotly
  - notebook
  - pip
