name: soil_moisture_swir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - plotly
  - notebook
  - pip
  - pip:
      - dominance-analysis
