name: soil_moisture_swir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - plotly
  - openpyxl
  - pip
  - pip:
      - mlxtend
      - clhs
      - dominance-analysis
